### ISSUE TITLE
#lang for each data format

### ISSUE THREAD

**Issue by bennn** [bennn/gtp-measure#1]
Make a (versioned?) #lang for each data format

Make sure `gtp-plot` understands the versions .... or `gtp-measure` can produce data that `gtp-plot` understands (the second sounds better, would avoid a dependency)

**Comment by bennn** [comment]
962fb77 adds two `#lang`s for gtp-plot to find

these langs should do some parsing & summarizing too

**Comment by camoy** [comment]
Can these langs provide the data instead of just producing a string? That way it's easier for other scripts to consume via `dynamic-require`.

**Comment by bennn** [comment]
Sounds good ... I think I'll use a special provide for that & add helper functions to this package:

- `(gtp-measure-require file)`, or something, gets the full data using `(dynamic-require file 'data)`
- `racket file` on the command-line does something nicer than `$ cat file`

**Comment by bennn** [comment]
7fc5057ee1ea08d200cd559a0f1a00ed6401ab78 adds simple things for `#lang gtp-measure/output/typed-untyped` datasets

- dataset bound / provided as `gtp-info`
- summary stats = num configs, min/max runtime, etc

#### Example file
```
#lang gtp-measure/output/typed-untyped
("00" ("cpu time: 5756 real time: 5758 gc time: 312" "cpu time: 5780 real time: 5776 gc time: 288"))
("01" ("cpu time: 127208 real time: 127133 gc time: 19236" "cpu time: 122168 real time: 122103 gc time: 19172"))
("10" ("cpu time: 28552 real time: 28541 gc time: 5192" "cpu time: 28400 real time: 28391 gc time: 5184"))
("11" ("cpu time: 5488 real time: 5490 gc time: 352" "cpu time: 5472 real time: 5473 gc time: 328"))
```

#### command line: racket file.rkt
```
dataset info:
- num configs: 4
- num timings: 8
- min time: 5472 ms
- max time: 127208 ms
- total time: 328824 ms
```

#### require 
```
#lang racket/base
(require (only-in "sieve.rktd" gtp-data))
(length gtp-data)
;; 4
```
